CREATE TABLE libro (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    titulo VARCHAR2(255) NOT NULL,
    autor VARCHAR2(255) NOT NULL,
    anio_publicacion NUMBER(4) NOT NULL,
    genero VARCHAR2(100) NOT NULL,
    PRIMARY KEY (id)
);

INSERT INTO libro (titulo, autor, anio_publicacion, genero) 
VALUES ('Cien años de soledad', 'Gabriel García Márquez', 1967, 'Novela');

INSERT INTO libro (titulo, autor, anio_publicacion, genero) 
VALUES ('1984', 'George Orwell', 1949, 'Distopía');

INSERT INTO libro (titulo, autor, anio_publicacion, genero) 
VALUES ('Don Quijote de la Mancha', 'Miguel de Cervantes', 1605, 'Novela');

INSERT INTO libro (titulo, autor, anio_publicacion, genero) 
VALUES ('El señor de los anillos', 'J. R. R. Tolkien', 1954, 'Fantasía');

INSERT INTO libro (titulo, autor, anio_publicacion, genero) 
VALUES ('Crimen y castigo', 'Fiódor Dostoyevski', 1866, 'Filosofía');